# Pull tomcat latest image from dockerhub 
From tomcat:latest

# Maintainer
MAINTAINER "DevOps By MK" 

# Copy webapps files into webapps directory
RUN cp -R  /usr/local/tomcat/webapps.dist/*  /usr/local/tomcat/webapps

# copy war file on to container 
COPY ./webapp/target/webapp.war /usr/local/tomcat/webapps
